### ISSUE TITLE
command for fine tuning may be wrong?

### ISSUE THREAD

**Issue by chenrxi** [ubc-vision/UniT#2]
![image](https://user-images.githubusercontent.com/60959000/142965557-c9a1b18c-ad1b-4e7c-a603-54aa46a7d614.png)
the config is probably wrong?
![image](https://user-images.githubusercontent.com/60959000/142965411-671a119c-f15b-4868-9e36-e31285739701.png)
And the sampling policy is different from other work because the instance in 10 shot mode is more than 10.

**Comment by siddheshk** [comment]
Apologies for the incorrect command. The command for finetuning should be 
```python
python scripts/finetune_VOC.py --config-file "configs/VOC/FT/{num}_shot/VOC-RCNN-101-C4-split{num}-ft.yaml" --num-gpus 4 --resume OUTPUT_DIR "Path/for/Checkpointing" MODEL.WEIGHTS "Path/to/Base/Training/Model/Weights" 
```

The splits for finetuning are directly taken from the following work: https://github.com/bingykang/Fewshot_Detection
Particularly, they treat k shot as having k labelled "images" instead of k labelled "instances". As each image can have multiple instances of the same object, some objects can end up having more than k instances.
